### ISSUE TITLE
[BUG] skim v3.0.0+ requires Rust 1.90+ but doesn't declare MSRV

### ISSUE THREAD

**Issue by pasteley** [skim-rs/skim#1017]
## Description

skim `v3.0.0` through `v4.0.0` uses `str::floor_char_boundary()` and `str::ceil_char_boundary()` which are part of the `round_char_boundary` feature, stabilized around Rust 1.90-1.94.

The crate compiles on the latest stable (`1.94.1`) but fails on older stable releases (e.g. `1.89`). Since no `rust-version`  is declared in `Cargo.toml`, users on slightly older stable toolchains get a confusing compile error with no indication of the required version.

## Error

```
error[E0658]: use of unstable library feature `round_char_boundary`
   --> src/tui/input.rs:196:30
    |
196 |         let pos = self.value.floor_char_boundary(new_pos as usize);
    |                              ^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #93743 <https://github.com/rust-lang/rust/issues/93743> for more information
```

## To reproduce

```bash
# With any stable rustc older than ~1.90
rustup run 1.89.0 cargo build
# fails with the above error
```

Works on `1.94.1` (specified in gh wf).

## Call to action

Bump `rust-version` to at least `1.90`,  or whichever version stabilized `round_char_boundary`

**Comment by LoricAndre** [comment]
Thank you for reporting this, it seems to have been introduced in `1.91.0`. I'll add this and release a patch version in a few hours
